# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFbWMjRbWUJcbzffdF_xavvstOmOdCsj
"""



# archivo: biodiversidad_zizur.py
import streamlit as st

st.set_page_config(page_title="Biodiversidad en Zizur", page_icon="🌿")

st.title("🌿 Quiz de Biodiversidad en Zizur")
st.write("Pon a prueba tus conocimientos sobre la flora y fauna de Zizur.")

preguntas = [
    {
        "pregunta": "¿Qué especie de ave es común en los parques de Zizur?",
        "opciones": ["Golondrina común", "Águila imperial", "Loro amazónico"],
        "respuesta": "Golondrina común"
    },
    {
        "pregunta": "¿Qué árbol autóctono puedes encontrar en la zona de Zizur?",
        "opciones": ["Olmo", "Baobab", "Pino de Monterrey"],
        "respuesta": "Olmo"
    },
    {
        "pregunta": "¿Qué insecto polinizador es fundamental en los campos de Zizur?",
        "opciones": ["Avispa", "Abeja", "Mosquito"],
        "respuesta": "Abeja"
    },
    {
        "pregunta": "¿Cuál es una flor silvestre habitual en primavera en Zizur?",
        "opciones": ["Rosa negra", "Amapola", "Girasol tropical"],
        "respuesta": "Amapola"
    }
]

score = 0
for i, q in enumerate(preguntas):
    st.subheader(f"Pregunta {i+1}")
    opcion = st.radio(q["pregunta"], q["opciones"], key=i)
    if opcion == q["respuesta"]:
        st.success("✅ ¡Correcto!")
        score += 1
    else:
        st.error(f"❌ Incorrecto. La respuesta era: {q['respuesta']}")

st.markdown("---")
st.header(f"Puntuación final: {score} de {len(preguntas)}")
if score == len(preguntas):
    st.balloons()
    st.success("¡Perfecto! Eres un experto/a en biodiversidad local 🐞🌸")
elif score >= len(preguntas) / 2:
    st.info("¡Muy bien! Pero aún puedes aprender más.")
else:
    st.warning("¡Ups! Toca repasar un poco más sobre la naturaleza de Zizur.")